version: '3'
services:
    main:
        build: .
        volumes:
            - ./src:/usr/app/src
            - ./gradle:/usr/app/gradle
            - ./.oxalis:/usr/app/.oxalis
        command: 'gradlew bootRun'
